import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'vite';

/**
 * Bakes the `@app/runtime` facade into `server/src/bundler/vendor/runtime.generated.ts`:
 * `runtimeModule` is React + react-dom + the Graphy chart runtime bundled from
 * the installed npm packages — all in, nothing externalized, so the whole
 * generated app shares exactly one React instance. `runtimeCss` is
 * react-renderer's compiled stylesheet, inlined into every preview.
 */

const appRoot = fileURLToPath(new URL('..', import.meta.url));
const facadeEntry = path.join(appRoot, 'scripts/runtime-facade.ts');
const outDir = path.join(appRoot, '.vendor-build');
const generatedFile = path.join(appRoot, 'server/src/bundler/vendor/runtime.generated.ts');

// Resolved off the package's `.` entry (the only exported subpath) so the
// sibling file is found without going through the exports map.
const vizEngineGraphConfig = fileURLToPath(
  new URL('./graph-config.mjs', import.meta.resolve('@graphysdk/viz-engine'))
);

await build({
  configFile: false,
  root: appRoot,
  logLevel: 'warn',
  define: { 'process.env.NODE_ENV': '"production"' },
  resolve: {
    alias: {
      // react-renderer reaches react-dom/server for text measurement; use the
      // browser build so nothing pulls the Node-only entry.
      'react-dom/server': 'react-dom/server.browser',
      // Upstream packaging bug: react-renderer's shared chunk (reachable from
      // its main entry) statically imports `@graphysdk/viz-engine/graph-config`,
      // but viz-engine's `publishConfig.exports` omits that subpath, so nothing
      // can resolve it through the package name. The file does ship, so alias to
      // its absolute path. Drop this once viz-engine exports the subpath.
      '@graphysdk/viz-engine/graph-config': vizEngineGraphConfig,
    },
  },
  build: {
    outDir,
    emptyOutDir: true,
    target: 'es2020',
    minify: 'esbuild',
    cssCodeSplit: false,
    lib: {
      entry: facadeEntry,
      formats: ['es'],
      fileName: () => 'runtime.mjs',
      cssFileName: 'runtime',
    },
    rollupOptions: {
      external: [],
      // React libraries ship "use client" directives that are meaningless once
      // bundled; silence the resulting noise so real warnings stay visible.
      onwarn(warning, warn) {
        if (warning.code === 'MODULE_LEVEL_DIRECTIVE') return;
        warn(warning);
      },
    },
  },
});

const runtimeModule = await readFile(path.join(outDir, 'runtime.mjs'), 'utf8');
const runtimeCss = await readFile(path.join(outDir, 'runtime.css'), 'utf8').catch(() => '');
await rm(outDir, { recursive: true, force: true });

await mkdir(path.dirname(generatedFile), { recursive: true });
await writeFile(
  generatedFile,
  [
    '/* eslint-disable */',
    '// GENERATED by scripts/build-vendor.mjs — do not edit by hand.',
    `export const runtimeModule = ${JSON.stringify(runtimeModule)};`,
    `export const runtimeCss = ${JSON.stringify(runtimeCss)};`,
    '',
  ].join('\n')
);

console.info(
  `[graph-codegen] vendor runtime generated (${(runtimeModule.length / 1024).toFixed(0)} kB js, ${(runtimeCss.length / 1024).toFixed(0)} kB css)`
);
